# Generated by Django 5.0.4 on 2024-05-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
