# Generated by Django 5.0.4 on 2024-05-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_alter_orders_paymentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oid',
            new_name='razor_pay_order_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='razor_pay_signature',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
