# Generated by Django 5.0.4 on 2024-05-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0005_rename_oid_orders_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='razor_pay_signature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
