# Generated by Django 5.0.4 on 2024-05-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0006_alter_orders_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='amountpaid',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='paymentstatus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='phone',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
