# Generated by Django 5.0.4 on 2024-05-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0007_orderupdate_amountpaid_orderupdate_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
