# Generated by Django 5.0.4 on 2024-05-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0008_orderupdate_razor_pay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
