# Generated by Django 5.0.4 on 2024-05-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0009_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
    ]
